# Generated by Django 5.0.1 on 2025-06-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Intake', 'Intake'), ('Burn', 'Burn')], max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('calories', models.PositiveIntegerField()),
            ],
        ),
    ]
